### ISSUE TITLE
vue2如何使用

### ISSUE THREAD

**Issue by jiangzhikele** [lloydzhou/graphin-vue#10]
您好，请问有vue2版本的分支代码吗

**Comment by lloydzhou** [comment]
我写的时候，并没有对vue2做兼容。

不过，可以把这个项目的UI组件部分使用vue2重写一份。逻辑并不复杂。

最主要的思想就是，核心的代码直接使用@antv/graphin这个包里面的。只把UI部分用vue重写替换@antv/graphin项目中的react部分。

**Comment by lloydzhou** [comment]
我觉得改写也并不复杂。
例如大多数的`Behavior`组件都使用了同一个方法`useBehaviorHook`去定义

**Comment by jiangzhikele** [comment]
好的，谢谢
