### ISSUE TITLE
依赖缺失

### ISSUE THREAD

**Issue by LiHuiOne** [lloydzhou/graphin-vue#15]
大佬，安装后，缺少这两个依赖：，请教下咋解决
import cloneDeep from '@antv/graphin/es/utils/cloneDeep'
import deepEqual from '@antv/graphin/es/utils/deepEqual'

**Comment by Tangcuyu** [comment]
我也遇到了类似问题，降低@antv/graphin的版本到"@antv/graphin": "2.6.7", 可以正常跑起来了

**Comment by lloydzhou** [comment]
import from lodash-es
