### ISSUE TITLE
可以使用在生产环境中吗

### ISSUE THREAD

**Issue by liect** [lloydzhou/graphin-vue#9]
如题,稳定吗

**Comment by liect** [comment]
README中的示例有语法错误
definecomponent -> defineComponent
<Graphin :data="data" :layout="layout"> -> <Graphin data={state.data} layout={state.layout}>

**Comment by lloydzhou** [comment]
1. 我自己的项目（其实是公司的项目）就有在使用
2. 这个项目只有UI部分是使用vue重写的。核心部分实际上是直接使用的`@antv/graphin`的源码。
> 采用这个逻辑可以减少将graphin从react改写成vue代码改动的量。减少改动也能**减少**引入新的bug
> 还有一个好处就是，如果graphin核心代码有更新或者有bug修复，其实不用重新安装 `antv-graphin-vue`只需要重新安装`@antv/graphin`就可以了。
